package setup

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"hctl/internal/project"
	"hctl/internal/rootfs"
)

const maxMetadataBytes = 64 << 10

var portableName = regexp.MustCompile(`^[a-z][a-z0-9-]{0,62}$`)

type ownedFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

type applyRecord struct {
	SchemaVersion     int         `json:"schema_version"`
	Generator         string      `json:"generator"`
	Harness           string      `json:"harness"`
	SourceFingerprint string      `json:"source_fingerprint"`
	Files             []ownedFile `json:"files"`
}

func Apply(p *project.Project, executable string) ([]string, error) {
	if !filepath.IsAbs(executable) {
		return nil, errors.New("managed MCP executable path must be absolute")
	}
	files, err := filesFor(p, executable)
	if err != nil {
		return nil, err
	}
	recordPath := applyRecordPath(p.Harness)
	prior, exists, legacy, err := loadApplyRecord(p.Root, p.Harness)
	if err != nil {
		return nil, err
	}
	priorFiles := map[string]ownedFile{}
	if exists {
		if prior.SchemaVersion != 1 || prior.Harness != p.Harness {
			return nil, errors.New("apply record is incompatible; remove the generated harness files manually")
		}
		for _, owned := range prior.Files {
			if !allowedOwnedPath(p.Harness, owned.Path, legacy) || priorFiles[owned.Path].Path != "" {
				return nil, errors.New("apply record contains an invalid path")
			}
			priorFiles[owned.Path] = owned
			actual, present, err := generatedHash(p.Root, owned.Path)
			if err != nil {
				return nil, err
			}
			if present && actual != owned.SHA256 {
				return nil, fmt.Errorf("generated file %s was changed; refusing to overwrite it", owned.Path)
			}
		}
	}
	for path := range files {
		if !allowedPath(p.Harness, path) {
			return nil, errors.New("generated harness path is not allowed")
		}
		_, present, err := generatedHash(p.Root, path)
		if err != nil {
			return nil, err
		}
		if present && priorFiles[path].Path == "" {
			return nil, fmt.Errorf("native file %s already exists without hctl ownership; refusing to overwrite it", path)
		}
	}

	paths := sortedKeys(files)
	owned := make([]ownedFile, 0, len(paths))
	for _, path := range paths {
		if err := rootfs.WriteAtomic(p.Root, path, files[path], 0o644); err != nil {
			return nil, err
		}
		owned = append(owned, ownedFile{Path: path, SHA256: rootfs.SHA256(files[path])})
	}
	for path := range priorFiles {
		if _, retained := files[path]; !retained {
			if err := rootfs.RemoveRegular(p.Root, path); err != nil {
				return nil, err
			}
		}
	}
	meta := applyRecord{SchemaVersion: 1, Generator: project.GeneratorVersion, Harness: p.Harness, SourceFingerprint: p.SourceFingerprint, Files: owned}
	metaBytes, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return nil, errors.New("cannot encode apply record")
	}
	if err := rootfs.WriteAtomic(p.Root, recordPath, append(metaBytes, '\n'), 0o644); err != nil {
		return nil, err
	}
	if legacy {
		if err := rootfs.RemoveRegular(p.Root, legacyRecordPath(p.Harness)); err != nil {
			return nil, err
		}
	}
	if err := Verify(p); err != nil {
		return nil, err
	}
	return append(paths, recordPath), nil
}

func Verify(p *project.Project) error {
	meta, exists, err := readApplyRecord(p.Root, applyRecordPath(p.Harness))
	if err != nil {
		return err
	}
	if !exists || meta.Generator != project.GeneratorVersion || meta.SourceFingerprint != p.SourceFingerprint || meta.Harness != p.Harness {
		return fmt.Errorf("%s setup is missing or stale; run hctl apply first", p.Harness)
	}
	if len(meta.Files) == 0 {
		return fmt.Errorf("%s setup is incomplete; run hctl apply first", p.Harness)
	}
	seen := map[string]bool{}
	for _, owned := range meta.Files {
		if seen[owned.Path] || !allowedPath(p.Harness, owned.Path) {
			return errors.New("apply record contains an invalid path")
		}
		seen[owned.Path] = true
		actual, present, err := generatedHash(p.Root, owned.Path)
		if err != nil || !present || actual != owned.SHA256 {
			return fmt.Errorf("%s generated file %s is missing or changed; run hctl apply first", p.Harness, owned.Path)
		}
	}
	return nil
}

func filesFor(p *project.Project, executable string) (map[string][]byte, error) {
	files := map[string][]byte{}
	header := fmt.Sprintf("<!-- Generated by %s from source %s. Safe to discard; edit portable source instead. -->\n\n", project.GeneratorVersion, p.SourceFingerprint)
	instructions := header + "# " + p.Name + "\n\n" + strings.TrimSpace(string(p.Instructions)) + "\n\n## Tool boundary\n\nThe `echo` MCP tool is managed. Native harness tools remain allowed and unmanaged.\n"
	if p.Harness == "claude" {
		files["CLAUDE.md"] = []byte(instructions)
		config := map[string]any{"mcpServers": map[string]any{"managed": map[string]any{"type": "stdio", "command": executable, "args": []string{"mcp", "serve", "."}}}}
		configBytes, err := json.MarshalIndent(config, "", "  ")
		if err != nil {
			return nil, errors.New("cannot encode Claude MCP configuration")
		}
		files[".mcp.json"] = append(configBytes, '\n')
		for _, skill := range p.Skills {
			files[fmt.Sprintf(".claude/skills/%s/SKILL.md", skill.Name)] = markGeneratedSkill(skill.Content, p.SourceFingerprint)
		}
	} else {
		files["AGENTS.md"] = []byte(instructions)
		files[".codex/config.toml"] = []byte("# Generated by " + project.GeneratorVersion + "; safe to discard.\n[mcp_servers.managed]\ncommand = " + strconv.Quote(executable) + "\nargs = [\"mcp\", \"serve\", \".\"]\n")
		for _, skill := range p.Skills {
			files[fmt.Sprintf(".agents/skills/%s/SKILL.md", skill.Name)] = markGeneratedSkill(skill.Content, p.SourceFingerprint)
		}
	}
	return files, nil
}

func markGeneratedSkill(content []byte, fingerprint string) []byte {
	marker := []byte("---\n")
	second := bytes.Index(content[len(marker):], marker)
	if second < 0 {
		return content
	}
	insert := len(marker) + second + len(marker)
	out := append([]byte{}, content[:insert]...)
	out = append(out, []byte(fmt.Sprintf("<!-- Generated by %s from source %s. Safe to discard. -->\n", project.GeneratorVersion, fingerprint))...)
	out = append(out, content[insert:]...)
	return out
}

func applyRecordPath(harness string) string {
	return fmt.Sprintf(".hctl/apply/%s.json", harness)
}

func legacyRecordPath(harness string) string {
	return fmt.Sprintf(".hctl/projections/%s.json", harness)
}

func loadApplyRecord(root, harness string) (applyRecord, bool, bool, error) {
	meta, exists, err := readApplyRecord(root, applyRecordPath(harness))
	if err != nil || exists {
		return meta, exists, false, err
	}
	meta, exists, err = readApplyRecord(root, legacyRecordPath(harness))
	return meta, exists, exists, err
}

func readApplyRecord(root, relative string) (applyRecord, bool, error) {
	var meta applyRecord
	data, _, exists, err := rootfs.ReadOptional(root, relative, maxMetadataBytes)
	if err != nil || !exists {
		return meta, exists, err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&meta); err != nil {
		return meta, false, errors.New("apply record is invalid")
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return meta, false, errors.New("apply record is invalid")
	}
	return meta, true, nil
}

func allowedPath(harness, path string) bool {
	if harness == "claude" {
		if path == "CLAUDE.md" || path == ".mcp.json" {
			return true
		}
		return generatedSkillPath(path, ".claude/skills/")
	}
	if path == "AGENTS.md" || path == ".codex/config.toml" {
		return true
	}
	return generatedSkillPath(path, ".agents/skills/")
}

func allowedOwnedPath(harness, path string, legacy bool) bool {
	return allowedPath(harness, path) || legacy && path == fmt.Sprintf(".hctl/manifests/%s.json", harness)
}

func generatedSkillPath(path, prefix string) bool {
	if !strings.HasPrefix(path, prefix) || !strings.HasSuffix(path, "/SKILL.md") {
		return false
	}
	name := strings.TrimSuffix(strings.TrimPrefix(path, prefix), "/SKILL.md")
	return portableName.MatchString(name) && !strings.Contains(name, "/")
}

func generatedHash(root, relative string) (string, bool, error) {
	data, _, exists, err := rootfs.ReadOptional(root, relative, 1<<20)
	if err != nil || !exists {
		return "", exists, err
	}
	return rootfs.SHA256(data), true, nil
}

func sortedKeys(values map[string][]byte) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
