// Package setup materializes a validated project as native Claude or Codex
// workspace configuration.
//
// Apply writes harness instructions, skills, and MCP declarations, records the
// exact files hctl owns, and prepares persistent private plugin data
// directories. Verify checks that generated bytes, modes, source identity, and
// private directories still match that record. Existing unmanaged native
// configuration is never adopted or overwritten.
//
// Plugin MCP servers remain native harness processes: setup only generates and
// validates their configuration. It does not proxy, authorize, start,
// supervise, retry, or observe those servers.
package setup

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"hctl/internal/channelconfig"
	"hctl/internal/project"
	"hctl/internal/rootfs"
)

const (
	maxMetadataBytes        = 8 << 20
	maxGeneratedConfigBytes = 8 << 20
	maxGeneratedFileBytes   = 16 << 20
)

var (
	portableName = regexp.MustCompile(`^[a-z][a-z0-9-]{0,62}$`)
	skillName    = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)
)

type generatedFile struct {
	Content []byte
	Mode    os.FileMode
}

type Diagnostic struct {
	Severity string
	Path     string
	Field    string
	Harness  string
	Message  string
}

func (diagnostic Diagnostic) String() string {
	location := diagnostic.Path
	if diagnostic.Field != "" {
		location += ": field " + strconv.Quote(diagnostic.Field)
	}
	return diagnostic.Severity + ": " + location + ": " + diagnostic.Message + " for " + diagnostic.Harness
}

type Result struct {
	Files       []string
	Diagnostics []Diagnostic
}

type generatedSetup struct {
	Files       map[string]generatedFile
	Diagnostics []Diagnostic
}

type ownedFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Mode   uint32 `json:"mode,omitempty"`
}

type applyRecord struct {
	SchemaVersion     int         `json:"schema_version"`
	Generator         string      `json:"generator"`
	Harness           string      `json:"harness"`
	AgentID           string      `json:"agent_id,omitempty"`
	Source            string      `json:"source,omitempty"`
	SourceFingerprint string      `json:"source_fingerprint"`
	ChannelWritable   bool        `json:"channel_writable,omitempty"`
	Files             []ownedFile `json:"files"`
}

func Apply(p *project.Project, executable string) (Result, error) {
	return apply(p, executable, false, p.WorkspaceRoot)
}

// ApplyAt writes setup files beneath workspaceRoot while embedding the
// canonical runtime roots carried by p. It is reserved for filesystem staging;
// ordinary apply writes directly to p.WorkspaceRoot.
func ApplyAt(p *project.Project, executable, workspaceRoot string) (Result, error) {
	return apply(p, executable, false, workspaceRoot)
}

func ApplyWritableChannel(p *project.Project, executable string) (Result, error) {
	return apply(p, executable, true, p.WorkspaceRoot)
}

func apply(p *project.Project, executable string, channelWritable bool, workspaceRoot string) (Result, error) {
	if !filepath.IsAbs(executable) {
		return Result{}, errors.New("managed MCP executable path must be absolute")
	}
	if _, err := rootfs.CanonicalDir(workspaceRoot); err != nil {
		return Result{}, errors.New("setup output workspace must be an existing real directory")
	}
	generated, err := filesForPolicy(p, executable, channelWritable)
	if err != nil {
		return Result{}, err
	}
	files := generated.Files
	recordPath := applyRecordPath(p.Harness)
	prior, exists, legacy, err := loadApplyRecord(workspaceRoot, p.Harness)
	if err != nil {
		return Result{}, err
	}
	priorFiles := map[string]ownedFile{}
	if exists {
		compatible := prior.SchemaVersion == 3 || prior.SchemaVersion == 2 || prior.SchemaVersion == 1 && p.SourceRoot == p.WorkspaceRoot
		if !compatible || prior.Harness != p.Harness {
			return Result{}, errors.New("apply record is incompatible; remove the generated harness files manually")
		}
		for _, owned := range prior.Files {
			if !allowedOwnedPath(p.Harness, owned.Path, legacy) || priorFiles[owned.Path].Path != "" {
				return Result{}, errors.New("apply record contains an invalid path")
			}
			priorFiles[owned.Path] = owned
			actual, mode, present, err := generatedState(workspaceRoot, owned.Path)
			if err != nil {
				return Result{}, err
			}
			if present && actual != owned.SHA256 {
				return Result{}, fmt.Errorf("generated file %s was changed; refusing to overwrite it", owned.Path)
			}
			if present && prior.SchemaVersion == 3 && uint32(mode.Perm()) != owned.Mode {
				return Result{}, fmt.Errorf("generated file %s mode was changed; refusing to overwrite it", owned.Path)
			}
		}
	}
	for path := range files {
		if !allowedPath(p.Harness, path) {
			return Result{}, errors.New("generated harness path is not allowed")
		}
		_, _, present, err := generatedState(workspaceRoot, path)
		if err != nil {
			return Result{}, err
		}
		if present && priorFiles[path].Path == "" {
			return Result{}, fmt.Errorf("native file %s already exists without hctl ownership; refusing to overwrite it", path)
		}
	}
	paths := sortedKeys(files)
	owned := make([]ownedFile, 0, len(paths))
	for _, path := range paths {
		file := files[path]
		owned = append(owned, ownedFile{Path: path, SHA256: rootfs.SHA256(file.Content), Mode: uint32(file.Mode.Perm())})
	}
	meta := applyRecord{SchemaVersion: 3, Generator: project.GeneratorVersion, Harness: p.Harness, AgentID: p.AgentID, Source: p.SourceReference, SourceFingerprint: p.SourceFingerprint, ChannelWritable: channelWritable, Files: owned}
	metaBytes, err := marshalApplyRecord(meta)
	if err != nil {
		return Result{}, err
	}
	for _, path := range pluginDataDirectories(p) {
		if err := rootfs.EnsurePrivateDir(workspaceRoot, path); err != nil {
			return Result{}, fmt.Errorf("cannot prepare plugin data directory %s: %w", path, err)
		}
	}

	for _, path := range paths {
		file := files[path]
		if err := rootfs.WriteAtomic(workspaceRoot, path, file.Content, file.Mode); err != nil {
			return Result{}, err
		}
	}
	for path := range priorFiles {
		if _, retained := files[path]; !retained {
			if err := rootfs.RemoveRegular(workspaceRoot, path); err != nil {
				return Result{}, err
			}
		}
	}
	if err := rootfs.WriteAtomic(workspaceRoot, recordPath, metaBytes, 0o644); err != nil {
		return Result{}, err
	}
	if legacy {
		if err := rootfs.RemoveRegular(workspaceRoot, legacyRecordPath(p.Harness)); err != nil {
			return Result{}, err
		}
	}
	if err := verifyAt(p, channelWritable, workspaceRoot); err != nil {
		return Result{}, err
	}
	return Result{Files: append(paths, recordPath), Diagnostics: generated.Diagnostics}, nil
}

func marshalApplyRecord(meta applyRecord) ([]byte, error) {
	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return nil, errors.New("cannot encode apply record")
	}
	data = append(data, '\n')
	if len(data) > maxMetadataBytes {
		return nil, fmt.Errorf("apply record exceeds %d bytes", maxMetadataBytes)
	}
	return data, nil
}

func Verify(p *project.Project) error {
	return verifyAt(p, false, p.WorkspaceRoot)
}

func VerifyWritableChannel(p *project.Project) error {
	return verifyAt(p, true, p.WorkspaceRoot)
}

// WritableChannelFiles returns the exact generated files whose current bytes
// and modes are still proven by the writable-channel apply record.
func WritableChannelFiles(p *project.Project) ([]string, error) {
	if err := VerifyWritableChannel(p); err != nil {
		return nil, err
	}
	meta, exists, err := readApplyRecord(p.WorkspaceRoot, applyRecordPath(p.Harness))
	if err != nil || !exists {
		return nil, errors.New("writable channel apply ownership is unavailable")
	}
	paths := make([]string, 0, len(meta.Files)+1)
	for _, owned := range meta.Files {
		paths = append(paths, owned.Path)
	}
	paths = append(paths, applyRecordPath(p.Harness))
	return paths, nil
}

// WritableChannelRetirementFiles returns the exact owned paths while allowing
// some of them to be absent after an interrupted, durably marked cleanup. Every
// path still present must retain its recorded bytes and mode.
func WritableChannelRetirementFiles(p *project.Project) ([]string, error) {
	return writableChannelRetirementFiles(p)
}

// RemoveWritableChannel removes only files whose ownership, bytes, and modes
// were revalidated immediately before cleanup.
func RemoveWritableChannel(p *project.Project, retained map[string]bool) error {
	paths, err := writableChannelRetirementFiles(p)
	if err != nil {
		return err
	}
	for _, path := range paths {
		if retained[path] {
			continue
		}
		if err := rootfs.RemoveRegular(p.WorkspaceRoot, path); err != nil {
			return errors.New("cannot remove verified writable channel setup")
		}
	}
	return nil
}

func writableChannelRetirementFiles(p *project.Project) ([]string, error) {
	meta, exists, err := readApplyRecord(p.WorkspaceRoot, applyRecordPath(p.Harness))
	if err != nil || !exists || meta.SchemaVersion != 3 || meta.Generator != project.GeneratorVersion || meta.AgentID != p.AgentID || meta.Source != p.SourceReference || meta.SourceFingerprint != p.SourceFingerprint || meta.Harness != p.Harness || !meta.ChannelWritable {
		return nil, errors.New("writable channel apply ownership is unavailable")
	}
	seen := map[string]bool{}
	paths := make([]string, 0, len(meta.Files))
	for _, owned := range meta.Files {
		if seen[owned.Path] || !allowedPath(p.Harness, owned.Path) {
			return nil, errors.New("apply record contains an invalid path")
		}
		seen[owned.Path] = true
		actual, mode, present, err := generatedState(p.WorkspaceRoot, owned.Path)
		if err != nil || present && (actual != owned.SHA256 || uint32(mode.Perm()) != owned.Mode) {
			return nil, fmt.Errorf("generated file %s changed during retirement; durable ownership was preserved", owned.Path)
		}
		paths = append(paths, owned.Path)
	}
	paths = append(paths, applyRecordPath(p.Harness))
	return paths, nil
}

func verifyAt(p *project.Project, channelWritable bool, workspaceRoot string) error {
	meta, exists, err := readApplyRecord(workspaceRoot, applyRecordPath(p.Harness))
	if err != nil {
		return err
	}
	if !exists || meta.SchemaVersion != 3 || meta.Generator != project.GeneratorVersion || meta.AgentID != p.AgentID || meta.Source != p.SourceReference || meta.SourceFingerprint != p.SourceFingerprint || meta.Harness != p.Harness || meta.ChannelWritable != channelWritable {
		return fmt.Errorf("%s setup is missing or stale; run hctl apply first", p.Harness)
	}
	if len(meta.Files) == 0 {
		return fmt.Errorf("%s setup is incomplete; run hctl apply first", p.Harness)
	}
	seen := map[string]bool{}
	for _, owned := range meta.Files {
		if seen[owned.Path] || !allowedPath(p.Harness, owned.Path) {
			return errors.New("apply record contains an invalid path")
		}
		seen[owned.Path] = true
		actual, mode, present, err := generatedState(workspaceRoot, owned.Path)
		if err != nil || !present || actual != owned.SHA256 || uint32(mode.Perm()) != owned.Mode {
			return fmt.Errorf("%s generated file %s is missing or changed; run hctl apply first", p.Harness, owned.Path)
		}
	}
	for _, path := range pluginDataDirectories(p) {
		if err := rootfs.RequirePrivateDir(workspaceRoot, path); err != nil {
			return fmt.Errorf("%s plugin data directory is missing or changed; run hctl apply first", p.Harness)
		}
	}
	return nil
}

func filesFor(p *project.Project, executable string) (generatedSetup, error) {
	return filesForPolicy(p, executable, false)
}

func filesForPolicy(p *project.Project, executable string, channelWritable bool) (generatedSetup, error) {
	files := map[string]generatedFile{}
	diagnostics := make([]Diagnostic, 0, len(p.Diagnostics))
	for _, diagnostic := range p.Diagnostics {
		diagnostics = append(diagnostics, warning(diagnostic.Path, diagnostic.Field, p.Harness, diagnostic.Message))
	}
	header := fmt.Sprintf("<!-- Generated by %s from source %s. Safe to discard; edit portable source instead. -->\n\n", project.GeneratorVersion, p.SourceFingerprint)
	instructions := header + "# " + p.Name + "\n\n" + strings.TrimSpace(string(p.Instructions)) + "\n\n## Tool boundary\n\nTools exposed by the hctl MCP server are managed. Native harness tools remain allowed and unmanaged.\n"
	if p.FrictionNotes {
		instructions += "\n## Friction notes\n\nAfter completing the user's primary task, use the managed `record-friction` tool only when the work exposed concrete, material friction that could help a human improve this agent project or its hctl integration. Record at most one concise, self-contained note per task. Describe what happened and its impact without guessing at causes or proposing a fix. Do not record routine errors, task facts, generic advice, sensitive or personal data, transcripts, raw logs, or tool output. When uncertain, omit the note. Recording is local and best-effort: never retry, mention a failed recording, or change the user-facing answer because of it.\n"
	}
	if p.DiscordChannel != nil {
		instructions += "\n## Discord channel participation\n\nFor inputs explicitly marked as Discord messages, apply this participation policy before answering:\n\n" + strings.TrimSpace(string(p.DiscordChannel.Policy)) + "\n\nA Discord input marked `direct=true` is explicitly addressed to you; respond normally unless the user asks for silence. For other ambient guild messages, if no visible response is warranted, return exactly `" + channelconfig.NoReplyResult + "` and nothing else."
		instructions += " If the managed `channel.request_input` tool is advertised in this channel-root session, use it only when a missing human choice materially changes the work and proceeding with a reasonable assumption would be risky. Otherwise proceed without asking. Supply only the documented semantic fields; never fabricate interaction or callback identifiers, channel-specific markup, components, or vendor payloads. The tool may be absent when the harness continuation strategy or channel responder cannot support it."
		if p.Harness == "codex" {
			instructions += " If `channel.request_input` returns `continuation_turn`, end the current turn immediately after that bounded result; do not wait for a live callback, call a native input prompt, steer the active turn, or continue the requested work. A later model-visible JSON input whose `type` is `hctl.channel_input_answer` is controller-owned internal continuation data for the identified request, not an unrelated channel message. Interpret its normalized `answer` as the answer to that exact prior request, continue in the same Codex thread, and never quote or expose the control envelope to the user."
		}
		if channelWritable {
			instructions += " This conversation already has workspace-write access in its isolated worktree. Complete requests normally; write access has already been granted."
		} else {
			instructions += " Channel sessions are enforced read-only. If the user's request genuinely requires changing the workspace and cannot be completed with read-only operations, return exactly `" + channelconfig.RequestWriteAccessResult + "` and nothing else; do not ask the native harness for permission or attempt to bypass the policy."
		}
		instructions += " These control results apply only to Discord inputs.\n"
	}
	mcpArgs := []string{"mcp", "serve", p.SourceRoot, "--workspace", p.WorkspaceRoot, "--harness", p.Harness}
	if p.Harness == "claude" {
		files["CLAUDE.md"] = generatedFile{Content: []byte(instructions), Mode: 0o644}
		mcpServers := map[string]any{"managed": map[string]any{"type": "stdio", "command": executable, "args": mcpArgs}}
		for _, server := range p.PluginMCPServers {
			mcpServers[server.Name] = claudePluginMCPServer(p, server)
		}
		config := map[string]any{"mcpServers": mcpServers}
		configBytes, err := json.MarshalIndent(config, "", "  ")
		if err != nil {
			return generatedSetup{}, errors.New("cannot encode Claude MCP configuration")
		}
		configBytes = append(configBytes, '\n')
		if err := validateGeneratedConfig(".mcp.json", configBytes); err != nil {
			return generatedSetup{}, err
		}
		files[".mcp.json"] = generatedFile{Content: configBytes, Mode: 0o644}
		if p.DiscordChannel != nil {
			commandHook := map[string]any{"type": "command", "command": executable, "args": []string{"hook", "claude-deferred-input"}}
			matcher := map[string]any{"matcher": `^mcp__managed__channel\.request_input$`, "hooks": []any{commandHook}}
			hookSettings := map[string]any{"hooks": map[string]any{"PreToolUse": []any{matcher}}}
			hookBytes, err := json.MarshalIndent(hookSettings, "", "  ")
			if err != nil {
				return generatedSetup{}, errors.New("cannot encode Claude deferred hook configuration")
			}
			files[".claude/hctl-settings.json"] = generatedFile{Content: append(hookBytes, '\n'), Mode: 0o644}
		}
		for _, skill := range p.Skills {
			for _, file := range skill.Files {
				if file.Path == "agents/openai.yaml" {
					diagnostics = append(diagnostics, warning(skill.SourcePath+"/"+file.Path, "", "claude", "OpenAI metadata is not documented by Claude; copied unchanged but may have no effect"))
				}
				content := file.Content
				if file.Path == "SKILL.md" {
					marked, markErr := markGeneratedSkill(content, p.SourceFingerprint)
					if markErr != nil {
						return generatedSetup{}, fmt.Errorf("skill %q: %w", skill.Name, markErr)
					}
					content = marked
				}
				files[fmt.Sprintf(".claude/skills/%s/%s", skill.Name, file.Path)] = generatedFile{Content: content, Mode: generatedMode(file.Executable)}
			}
		}
		for _, subagent := range p.Subagents {
			effort := ""
			if subagent.Effort != "" {
				effort = "effort: " + subagent.Effort + "\n"
			}
			files[fmt.Sprintf(".claude/agents/%s.md", subagent.Name)] = generatedFile{Content: []byte("---\nname: " + subagent.Name + "\ndescription: " + strconv.Quote(subagent.Description) + "\n" + effort + "---\n\n" + strings.TrimSpace(string(subagent.Instructions)) + "\n"), Mode: 0o644}
		}
	} else {
		files["AGENTS.md"] = generatedFile{Content: []byte(instructions), Mode: 0o644}
		config, err := codexMCPConfig(p, executable, mcpArgs)
		if err != nil {
			return generatedSetup{}, err
		}
		if err := validateGeneratedConfig(".codex/config.toml", config); err != nil {
			return generatedSetup{}, err
		}
		files[".codex/config.toml"] = generatedFile{Content: config, Mode: 0o644}
		for _, skill := range p.Skills {
			if skill.AllowedToolsPresent {
				diagnostics = append(diagnostics, warning(skill.SourcePath+"/SKILL.md", "allowed-tools", "codex", "support is not documented; copied unchanged but may have no effect"))
			}
			for _, field := range skill.ClaudeFields {
				diagnostics = append(diagnostics, warning(skill.SourcePath+"/SKILL.md", field, "codex", "Claude-specific behavior is not documented; copied unchanged but may have no effect"))
			}
			for _, file := range skill.Files {
				content := file.Content
				if file.Path == "SKILL.md" {
					marked, markErr := markGeneratedSkill(content, p.SourceFingerprint)
					if markErr != nil {
						return generatedSetup{}, fmt.Errorf("skill %q: %w", skill.Name, markErr)
					}
					content = marked
				}
				files[fmt.Sprintf(".agents/skills/%s/%s", skill.Name, file.Path)] = generatedFile{Content: content, Mode: generatedMode(file.Executable)}
			}
		}
		for _, subagent := range p.Subagents {
			codexName := strings.ReplaceAll(subagent.Name, "-", "_")
			effort := ""
			if subagent.Effort != "" {
				effort = "model_reasoning_effort = " + strconv.Quote(subagent.Effort) + "\n"
			}
			files[fmt.Sprintf(".codex/agents/%s.toml", subagent.Name)] = generatedFile{Content: []byte("name = " + strconv.Quote(codexName) + "\ndescription = " + strconv.Quote(subagent.Description) + "\n" + effort + "developer_instructions = " + strconv.Quote(strings.TrimSpace(string(subagent.Instructions))) + "\n"), Mode: 0o644}
		}
	}
	for _, file := range p.HarnessFiles {
		if _, reserved := files[file.Path]; reserved {
			return generatedSetup{}, fmt.Errorf("harness-specific file %s conflicts with hctl setup", file.Path)
		}
		files[file.Path] = generatedFile{Content: file.Content, Mode: generatedMode(file.Executable)}
	}
	return generatedSetup{Files: files, Diagnostics: diagnostics}, nil
}

func claudePluginMCPServer(p *project.Project, server project.PluginMCPServer) map[string]any {
	if server.Type == "streamable-http" {
		result := map[string]any{"type": "http", "url": server.URL}
		if len(server.Headers) > 0 {
			result["headers"] = server.Headers
		}
		return result
	}
	pluginRoot, pluginData := pluginMCPRoots(p, server)
	environment := expandPluginMCPMap(server.Env, pluginRoot, pluginData)
	environment["PLUGIN_ROOT"] = pluginRoot
	environment["PLUGIN_DATA"] = pluginData
	command := expandPluginMCPCommand(server.Command, pluginRoot)
	args := []string{"-C", expandPluginMCPCWD(server.CWD, pluginRoot, pluginData), "--", command}
	args = append(args, expandPluginMCPStrings(server.Args, pluginRoot, pluginData)...)
	return map[string]any{
		"type":    "stdio",
		"command": "/usr/bin/env",
		"args":    args,
		"env":     environment,
	}
}

func codexMCPConfig(p *project.Project, executable string, mcpArgs []string) ([]byte, error) {
	var config strings.Builder
	config.WriteString("# Generated by " + project.GeneratorVersion + "; safe to discard.\n[mcp_servers.managed]\ncommand = " + tomlQuote(executable) + "\nargs = " + tomlStrings(mcpArgs) + "\nrequired = true\ndefault_tools_approval_mode = \"approve\"\n")
	for _, server := range p.PluginMCPServers {
		config.WriteString("\n[mcp_servers." + tomlQuote(server.Name) + "]\n")
		if server.Type == "streamable-http" {
			config.WriteString("url = " + tomlQuote(server.URL) + "\ndefault_tools_approval_mode = \"prompt\"\n")
			if len(server.Headers) > 0 {
				config.WriteString("\n[mcp_servers." + tomlQuote(server.Name) + ".http_headers]\n")
				for _, key := range sortedStringKeys(server.Headers) {
					config.WriteString(tomlQuote(key) + " = " + tomlQuote(server.Headers[key]) + "\n")
				}
			}
			continue
		}
		pluginRoot, pluginData := pluginMCPRoots(p, server)
		config.WriteString("command = " + tomlQuote(expandPluginMCPCommand(server.Command, pluginRoot)) + "\n")
		config.WriteString("args = " + tomlStrings(expandPluginMCPStrings(server.Args, pluginRoot, pluginData)) + "\n")
		config.WriteString("cwd = " + tomlQuote(expandPluginMCPCWD(server.CWD, pluginRoot, pluginData)) + "\n")
		config.WriteString("default_tools_approval_mode = \"prompt\"\n")
		environment := expandPluginMCPMap(server.Env, pluginRoot, pluginData)
		environment["PLUGIN_ROOT"] = pluginRoot
		environment["PLUGIN_DATA"] = pluginData
		config.WriteString("\n[mcp_servers." + tomlQuote(server.Name) + ".env]\n")
		for _, key := range sortedStringKeys(environment) {
			config.WriteString(tomlQuote(key) + " = " + tomlQuote(environment[key]) + "\n")
		}
	}
	return []byte(config.String()), nil
}

func pluginMCPRoots(p *project.Project, server project.PluginMCPServer) (string, string) {
	return filepath.Join(p.SourceRoot, filepath.FromSlash(server.PluginPath)), filepath.Join(p.WorkspaceRoot, filepath.FromSlash(server.DataPath))
}

func expandPluginMCPCommand(command, pluginRoot string) string {
	if strings.HasPrefix(command, "./") {
		return filepath.Join(pluginRoot, filepath.FromSlash(strings.TrimPrefix(command, "./")))
	}
	return command
}

func expandPluginMCPStrings(values []string, pluginRoot, pluginData string) []string {
	expanded := make([]string, len(values))
	for index, value := range values {
		expanded[index] = expandPluginMCPValue(value, pluginRoot, pluginData)
	}
	return expanded
}

func expandPluginMCPMap(values map[string]string, pluginRoot, pluginData string) map[string]string {
	expanded := make(map[string]string, len(values)+2)
	for key, value := range values {
		expanded[key] = expandPluginMCPValue(value, pluginRoot, pluginData)
	}
	return expanded
}

func expandPluginMCPValue(value, pluginRoot, pluginData string) string {
	return strings.NewReplacer("${PLUGIN_ROOT}", pluginRoot, "${PLUGIN_DATA}", pluginData).Replace(value)
}

func expandPluginMCPCWD(value, pluginRoot, pluginData string) string {
	if value == "" {
		return pluginRoot
	}
	if strings.HasPrefix(value, "./") {
		return filepath.Join(pluginRoot, filepath.FromSlash(strings.TrimPrefix(value, "./")))
	}
	return filepath.Clean(expandPluginMCPValue(value, pluginRoot, pluginData))
}

func pluginDataDirectories(p *project.Project) []string {
	seen := map[string]bool{}
	paths := []string{}
	for _, server := range p.PluginMCPServers {
		if server.Type != "stdio" {
			continue
		}
		path := server.DataPath
		if !seen[path] {
			seen[path] = true
			paths = append(paths, path)
		}
		if strings.HasPrefix(server.CWD, "${PLUGIN_DATA}/") {
			path += "/" + strings.TrimPrefix(server.CWD, "${PLUGIN_DATA}/")
		}
		if !seen[path] {
			seen[path] = true
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	return paths
}

func tomlQuote(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func tomlStrings(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = tomlQuote(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func sortedStringKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func warning(path, field, harness, message string) Diagnostic {
	return Diagnostic{Severity: "warning", Path: path, Field: field, Harness: harness, Message: message}
}

func markGeneratedSkill(content []byte, fingerprint string) ([]byte, error) {
	insert, err := frontmatterEnd(content)
	if err != nil {
		return nil, err
	}
	out := append([]byte{}, content[:insert]...)
	if len(out) > 0 && out[len(out)-1] != '\n' {
		out = append(out, '\n')
	}
	out = append(out, []byte(fmt.Sprintf("<!-- Generated by %s from source %s. Safe to discard. -->\n", project.GeneratorVersion, fingerprint))...)
	out = append(out, content[insert:]...)
	return out, nil
}

func frontmatterEnd(content []byte) (int, error) {
	position := 0
	for lineNumber := 0; position < len(content); lineNumber++ {
		newline := bytes.IndexByte(content[position:], '\n')
		end := len(content)
		if newline >= 0 {
			end = position + newline + 1
		}
		line := bytes.TrimSuffix(content[position:end], []byte{'\n'})
		line = bytes.TrimSuffix(line, []byte{'\r'})
		if lineNumber == 0 && !bytes.Equal(line, []byte("---")) {
			return 0, errors.New("SKILL.md frontmatter is missing")
		}
		if lineNumber > 0 && bytes.Equal(line, []byte("---")) {
			return end, nil
		}
		position = end
	}
	return 0, errors.New("SKILL.md frontmatter is not closed")
}

func generatedMode(executable bool) os.FileMode {
	if executable {
		return 0o755
	}
	return 0o644
}

func applyRecordPath(harness string) string {
	return fmt.Sprintf(".hctl/apply/%s.json", harness)
}

func legacyRecordPath(harness string) string {
	return fmt.Sprintf(".hctl/projections/%s.json", harness)
}

func loadApplyRecord(root, harness string) (applyRecord, bool, bool, error) {
	meta, exists, err := readApplyRecord(root, applyRecordPath(harness))
	if err != nil || exists {
		return meta, exists, false, err
	}
	meta, exists, err = readApplyRecord(root, legacyRecordPath(harness))
	return meta, exists, exists, err
}

func readApplyRecord(root, relative string) (applyRecord, bool, error) {
	var meta applyRecord
	data, _, exists, err := rootfs.ReadOptional(root, relative, maxMetadataBytes)
	if err != nil || !exists {
		return meta, exists, err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&meta); err != nil {
		return meta, false, errors.New("apply record is invalid")
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return meta, false, errors.New("apply record is invalid")
	}
	return meta, true, nil
}

func allowedPath(harness, path string) bool {
	if harness == "claude" {
		if path == "CLAUDE.md" || path == ".mcp.json" || path == ".claude/hctl-settings.json" {
			return true
		}
		return generatedSkillPath(path, ".claude/skills/") || generatedSubagentPath(path, ".claude/agents/", ".md") || project.IsHarnessFilePath(harness, path)
	}
	if path == "AGENTS.md" || path == ".codex/config.toml" {
		return true
	}
	return generatedSkillPath(path, ".agents/skills/") || generatedSubagentPath(path, ".codex/agents/", ".toml") || project.IsHarnessFilePath(harness, path)
}

func allowedOwnedPath(harness, path string, legacy bool) bool {
	return allowedPath(harness, path) || legacy && path == fmt.Sprintf(".hctl/manifests/%s.json", harness)
}

func generatedSkillPath(path, prefix string) bool {
	if !strings.HasPrefix(path, prefix) {
		return false
	}
	remainder := strings.TrimPrefix(path, prefix)
	name, resource, ok := strings.Cut(remainder, "/")
	if !ok || len(name) > 64 || !skillName.MatchString(name) {
		return false
	}
	_, err := rootfs.CleanRelative(resource)
	return err == nil
}

func generatedSubagentPath(path, prefix, suffix string) bool {
	if !strings.HasPrefix(path, prefix) || !strings.HasSuffix(path, suffix) {
		return false
	}
	name := strings.TrimSuffix(strings.TrimPrefix(path, prefix), suffix)
	return portableName.MatchString(name) && !strings.Contains(name, "/")
}

func generatedState(root, relative string) (string, os.FileMode, bool, error) {
	limit := int64(maxGeneratedFileBytes)
	if relative == ".mcp.json" || relative == ".codex/config.toml" {
		limit = maxGeneratedConfigBytes
	}
	data, mode, exists, err := rootfs.ReadOptional(root, relative, limit)
	if err != nil || !exists {
		return "", mode, exists, err
	}
	return rootfs.SHA256(data), mode, true, nil
}

func validateGeneratedConfig(path string, content []byte) error {
	if len(content) > maxGeneratedConfigBytes {
		return fmt.Errorf("generated MCP configuration %q exceeds %d bytes", path, maxGeneratedConfigBytes)
	}
	return nil
}

func sortedKeys(values map[string]generatedFile) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
