#!/bin/sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
tools_root="$repo_root/.tools"
go="$tools_root/go/bin/go"

fail() {
  echo "clean-install check: $*" >&2
  exit 1
}

assert_file() {
  [ -f "$1" ] || fail "expected file $1"
}

assert_contains() {
  grep -F "$2" "$1" >/dev/null || fail "$1 does not contain: $2"
}

if [ ! -x "$go" ]; then
  fail "repository-local Go is missing; run ./scripts/bootstrap-tools.sh"
fi

scratch=$(mktemp -d "${TMPDIR:-/tmp}/hctl-clean-install.XXXXXX")
scratch=$(CDPATH= cd -- "$scratch" && pwd -P)
cleanup() {
  rm -rf -- "$scratch"
}
trap cleanup EXIT HUP INT TERM

install_prefix="$scratch/prefix"
fake_bin="$scratch/fake-bin"
workspace="$scratch/workspace"
missing_runtime_workspace="$scratch/missing-runtime-workspace"
installed_hctl="$install_prefix/bin/hctl"
fake_codex="$fake_bin/codex"
mkdir -p "$install_prefix/bin" "$fake_bin" "$workspace" "$missing_runtime_workspace"

printf '%s\n' \
  '#!/bin/sh' \
  'if [ "$#" -eq 1 ] && [ "$1" = "--version" ]; then' \
  '  printf "%s\n" "codex-cli 0.144.1"' \
  '  exit 0' \
  'fi' \
  'printf "%s\n" "fake Codex supports only --version" >&2' \
  'exit 64' >"$fake_codex"
chmod 755 "$fake_codex"

(
  cd "$repo_root"
  GOCACHE="$scratch/go-build-cache" \
    GOMODCACHE="$tools_root/cache/mod" \
    GOTOOLCHAIN=local \
    "$go" build -mod=readonly -o "$installed_hctl" ./cmd/hctl
)
assert_file "$installed_hctl"

apply_output="$scratch/apply.out"
apply_error="$scratch/apply.err"
PATH="$fake_bin:/usr/bin:/bin" "$installed_hctl" apply \
  "$repo_root/examples/minimal" \
  --workspace "$workspace" \
  --harness codex \
  --command "$fake_codex" \
  >"$apply_output" 2>"$apply_error"

assert_file "$workspace/AGENTS.md"
assert_file "$workspace/.codex/config.toml"
assert_file "$workspace/.agents/skills/echo/SKILL.md"
assert_file "$workspace/.agents/skills/echo/references/tool-boundary.md"
assert_file "$workspace/.hctl/apply/codex.json"
cmp -s \
  "$repo_root/examples/minimal/skills/echo/references/tool-boundary.md" \
  "$workspace/.agents/skills/echo/references/tool-boundary.md" || fail "generated skill resource differs from authored source"
assert_contains "$workspace/AGENTS.md" "# minimal"
assert_contains "$workspace/.agents/skills/echo/SKILL.md" "<!-- Generated by hctl/"
assert_contains "$workspace/.agents/skills/echo/SKILL.md" "name: echo"
assert_contains "$workspace/.agents/skills/echo/SKILL.md" "[the tool-boundary reference](references/tool-boundary.md)"
assert_contains "$workspace/.codex/config.toml" "command = \"$installed_hctl\""
assert_contains "$workspace/.codex/config.toml" "\"$repo_root/examples/minimal\""
assert_contains "$workspace/.codex/config.toml" "\"--workspace\", \"$workspace\""
assert_contains "$workspace/.codex/config.toml" '"--harness", "codex"'
assert_contains "$workspace/.codex/config.toml" "required = true"
assert_contains "$apply_output" "managed tools=echo via MCP; native harness tools allowed and unmanaged"
assert_contains "$apply_output" "next: cd $workspace && codex"
[ ! -e "$workspace/CLAUDE.md" ] || fail "Codex apply generated Claude setup"
[ ! -e "$workspace/.mcp.json" ] || fail "Codex apply generated Claude MCP setup"

missing_runtime_output="$scratch/missing-runtime.out"
set +e
PATH="$fake_bin" "$installed_hctl" apply \
  "$repo_root/spikes/polyglot-tools/fixture" \
  --workspace "$missing_runtime_workspace" \
  --harness codex \
  --command "$fake_codex" \
  >"$missing_runtime_output" 2>&1
missing_runtime_status=$?
set -e
[ "$missing_runtime_status" -ne 0 ] || fail "apply succeeded without the authored TypeScript runtime"
assert_contains "$missing_runtime_output" "hctl: deno is required for authored tools"
[ ! -e "$missing_runtime_workspace/AGENTS.md" ] || fail "failed apply wrote native instructions"
[ ! -e "$missing_runtime_workspace/.codex/config.toml" ] || fail "failed apply wrote native MCP configuration"

printf '%s\n' "PASS built with $($go version) into an isolated install prefix"
printf '%s\n' "PASS applied examples/minimal with fake Codex and installed MCP command"
printf '%s\n' "PASS missing authored-tool runtime failed clearly before native setup"
